import type { Task } from "@/types/task";
import type { DailyState } from "@/types/task";
import { getCompletionPercentage, getEarnedXp } from "./tasks";

/**
 * Get today's ISO date string (YYYY-MM-DD) in the user's local timezone.
 *
 * Deliberately not `toISOString()`, which formats in UTC: for any timezone
 * ahead of UTC (the default here is Asia/Kolkata, +05:30) that reports
 * yesterday's date during the early hours of the morning, so the app would
 * load the wrong day's tasks until 05:30 local time.
 */
export function getTodayDate(): string {
  return toLocalDateString(new Date());
}

/**
 * Format a Date as YYYY-MM-DD using its local calendar fields.
 */
export function toLocalDateString(date: Date): string {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}

/**
 * ISO weekday number for a date (1 = Monday … 7 = Sunday), matching the
 * encoding used by the `recurrence_days` and `teaching_days` columns.
 */
export function getIsoWeekday(date: Date = new Date()): number {
  const day = date.getDay(); // 0 = Sunday
  return day === 0 ? 7 : day;
}

/**
 * Create a fresh daily state for a given date.
 */
export function createDailyState(date: string, tasks: Task[]): DailyState {
  const dateTasks = tasks.filter((t) => t.date === date);
  return {
    date,
    tasks: dateTasks,
    totalXpEarned: getEarnedXp(dateTasks),
    completionPercentage: getCompletionPercentage(dateTasks),
  };
}

/**
 * Check if a new day has started relative to a stored date.
 */
export function isNewDay(storedDate: string): boolean {
  return getTodayDate() !== storedDate;
}

/**
 * Generate today's recurring tasks from a template set.
 * Each recurring task gets a fresh instance for today's date.
 * NOTE: This is a pure function for testing. Actual task generation
 * happens server-side via the recurring template repository.
 * IDs are generated by the database (UUID).
 */
export function generateRecurringTasks(
  recurringTemplates: Task[],
  date: string
): Task[] {
  return recurringTemplates.map((template) => ({
    ...template,
    id: "", // Will be set by database
    date,
    completed: false,
    completedAt: undefined,
  }));
}

/**
 * Carry forward specific incomplete tasks from a previous day to today.
 * NOTE: This is a pure function for testing. Actual carry-forward
 * happens server-side via the task repository.
 * IDs are generated by the database (UUID).
 */
export function carryForwardTasks(tasks: Task[], date: string): Task[] {
  return tasks
    .filter((t) => !t.completed)
    .map((t) => ({
      ...t,
      id: "", // Will be set by database
      date,
    }));
}

/**
 * Recalculate daily state from the current tasks.
 */
export function recalculateDailyState(state: DailyState): DailyState {
  return {
    ...state,
    totalXpEarned: getEarnedXp(state.tasks),
    completionPercentage: getCompletionPercentage(state.tasks),
  };
}
